services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Use port 80 for production
    environment:
      - REACT_APP_BASE_URL=$$REACT_APP_BASE_URL  # Escape $ for GitHub Actions secrets
    depends_on:
      - backend  # Ensures backend is started before frontend
    stdin_open: false  # Disable stdin in production
    tty: false  # Disable tty in production
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=$$MONGODB_URI  # Escape $ for GitHub Actions secrets
      - JWT_SECRET=$$JWT_SECRET  # Escape $ for GitHub Actions secrets
      - OPENAI_API_KEY=$$OPENAI_API_KEY  # Escape $ for GitHub Actions secrets
      - CORS_ORIGIN=$$CORS_ORIGIN  # Escape $ for GitHub Actions secrets
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
