services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env  # Reference the .env file here
    stdin_open: false  # Disable stdin in production
    tty: false  # Disable tty in production
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - .env  # Reference the .env file here
    networks:
      - app-network
      
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
