name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - production  # Trigger the workflow on PR to production branch
  push:
    branches:
      - production  # Trigger the workflow when changes are pushed to the production branch

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Checkout the code
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # Set up Docker Buildx
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     # Install Docker Compose
  #     - name: Install Docker Compose
  #       run: |
  #         sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #         sudo chmod +x /usr/local/bin/docker-compose

  #     # Cache Docker layers
  #     - name: Cache Docker layers
  #       uses: actions/cache@v2
  #       with:
  #         path: /tmp/.buildx-cache
  #         key: ${{ runner.os }}-buildx-${{ github.sha }}
  #         restore-keys: |
  #           ${{ runner.os }}-buildx-

  #     # Build frontend and backend Docker images
  #     - name: Build frontend Docker image
  #       run: docker-compose -f docker-compose.yml build frontend

  #     - name: Build backend Docker image
  #       run: docker-compose -f docker-compose.yml build backend

  #     # Push Docker images to a registry (if using Docker Hub, GitHub Container Registry, etc.)
  #     - name: Push Docker images
  #       run: |
  #         echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #         docker-compose -f docker-compose.yml push frontend
  #         docker-compose -f docker-compose.yml push backend
  deploy:
    runs-on: ubuntu-latest
    # needs: build  # This job depends on the build job

    steps:
      - name: Get Timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run String Replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x "**/node_modules/*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Template-Generator
          environment_name: Template-Generator-dev 
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-west-2
          deployment_package: deploy.zip

