name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - production  # Trigger the workflow on PR to production branch
  push:
    branches:
      - production  # Trigger the workflow when changes are pushed to the production branch
env:    
  REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}



jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Template-Generator
        environment_name: Template-Generator-prod
        region: us-west-2
        deployment_package: deploy.zip