name: CI/CD Pipeline
on:
  pull_request:
    branches:
      - production  # Trigger workflow on PR to production branch
  push:
    branches:
      - production  # Trigger workflow on push to production branch

env:
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Prepare Backend Deployment Package
        working-directory: ./back-end
        run: zip -r --quiet backend-deploy.zip . -x '*.git*'

      - name: Deploy Backend to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Template-Generator
          environment_name: Template-Generator-backend
          version_label: 2
          region: us-west-2
          deployment_package: ./back-end/backend-deploy.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Prepare Frontend Deployment Package
        working-directory: ./frontend
        run: zip -r --quiet frontend-deploy.zip . -x '*.git*'

      - name: Deploy Frontend to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Template-Generator
          environment_name: Template-Generator-frontend
          version_label: 2
          region: us-west-2
          deployment_package: ./frontend/frontend-deploy.zip
